### ISSUE TITLE
How to logout/clear session?

### ISSUE THREAD

**Issue by anninosk** [livechat/chat-window-android#29] opened 2019-10-31 10:59 UTC
Is there a way to reset the chat by logging out or clearing session? On your ios version there is a mehod ```clearSession``` but on Android there is nothing to do so. please help

**Comment by abdulla-allaith** [comment] 2020-01-08 07:28
+1

**Comment by nomyzs** [comment] 2021-05-10 12:06
This seems like a duplicate of #17.
@anninosk and @abdulla-allaith please refer there for suggested solution.

Thanks :)

**Closed by nomyzs** 2021-05-10 12:06 UTC
