### ISSUE TITLE
Allow open external link

### ISSUE THREAD

**Issue by ArcherEmiya05** [livechat/chat-window-android#50] opened 2020-10-02 09:37 UTC
I tried to take a local copy of this project and one thing that our team noticed is that links within the chats can't be automatically open via another browser. We know that it has something to do with `shouldOverrideUrlLoading` in `ChatWindowView.class` but there is also a method `handleUri()`. What changes do we need to perform to allow link/uri intents so we can open a link via browser app. We do not want to break the existing logic of the `handleUri()` methods thus we ask for your guidance on this. This also could probably a feature request. We tried to change the code to adding an Intent and returning true on `shouldOverrideUrlLoading` but after returning in the app, the LiveChat windows become empty.

      `private boolean handleUri(WebView webView, final Uri uri) {
            String uriString = uri.toString();
            boolean facebookLogin = uriString.matches("https://.+facebook.+(/dialog/oauth\\?|/login\\.php\\?|/dialog/return/arbiter\\?).+");

            if (facebookLogin) {
                return false;
            } else {
                if (webViewPopup != null) {
                    webViewPopup.setVisibility(GONE);
                    removeView(webViewPopup);
                    webViewPopup = null;
                }

                String originalUrl = webView.getOriginalUrl();

                if (uriString.equals(originalUrl) || isSecureLivechatIncDoamin(uri.getHost())){//uri.getHost().contains("secure-lc.livechatinc.com")) {
                    return false;
                } else {
                    if (chatWindowListener != null/* && chatWindowListener.handleUri(uri)*/) {
                        return true;
                    }
                    else {
                        try {
                            Intent intent = new Intent(Intent.ACTION_VIEW, uri);
                            getContext().startActivity(intent);
                        }
                        catch (Exception e){
                            Toast.makeText(getContext(), "Error : " + e.getMessage(), Toast.LENGTH_SHORT).show();
                        }
                    }

                    return true;
                }
            }
        }`

**Comment by ArcherEmiya05** [comment] 2020-10-02 09:38
> 
> 
> I tried to take a local copy of this project and one thing that our team noticed is that links within the chats can't be automatically open via another browser. We know that it has something to do with `shouldOverrideUrlLoading` in `ChatWindowView.class` but there is also a method `handleUri()`. What changes do we need to perform to allow link/uri intents so we can open a link via browser app. We do not want to break the existing logic of the `handleUri()` methods thus we ask for your guidance on this. This also could probably a feature request.
> 
> `private boolean handleUri(WebView webView, final Uri uri) {
> String uriString = uri.toString();
> boolean facebookLogin = uriString.matches("https://.+facebook.+(/dialog/oauth\?|/login\.php\?|/dialog/return/arbiter\?).+");
> 
> ```
>         if (facebookLogin) {
>             return false;
>         } else {
>             if (webViewPopup != null) {
>                 webViewPopup.setVisibility(GONE);
>                 removeView(webViewPopup);
>                 webViewPopup = null;
>             }
> 
>             String originalUrl = webView.getOriginalUrl();
> 
>             if (uriString.equals(originalUrl) || isSecureLivechatIncDoamin(uri.getHost())){//uri.getHost().contains("secure-lc.livechatinc.com")) {
>                 return false;
>             } else {
>                 if (chatWindowListener != null/* && chatWindowListener.handleUri(uri)*/) {
>                     return true;
>                 }
>                 else {
>                     try {
>                         Intent intent = new Intent(Intent.ACTION_VIEW, uri);
>                         getContext().startActivity(intent);
>                     }
>                     catch (Exception e){
>                         Toast.makeText(getContext(), "Error : " + e.getMessage(), Toast.LENGTH_SHORT).show();
>                     }
>                 }
> 
>                 return true;
>             }
>         }
>     }`
> ```

**Comment by ArcherEmiya05** [comment] 2020-10-02 12:18
Already fix it by replacing the last else statement

        ` else {
                    if (chatWindowListener != null/* && chatWindowListener.handleUri(uri)*/) {
                        try {
                            Intent intent = new Intent(Intent.ACTION_VIEW, uri);
                            getContext().startActivity(intent);
                        }
                        catch (Exception e){
                            e.printStackTrace();
                            Toast.makeText(getContext(), "Error : " + e.getMessage(), Toast.LENGTH_SHORT).show();
                        }
                        return true;
                    }

                    return true;
                }`

**Comment by nomyzs** [comment] 2021-06-01 12:10
Hello @ArcherEmiya05 !

Thanks for reaching out and apologies for late response.
Glad you made it work for you!
Looking at your modified piece of code in your update makes me believe that in your case if you just specify your [ChatWindowEventsListener](https://github.com/livechat/chat-window-android#chatwindoweventslistener) and return `false` in your overwritten `handleUri` method this should work as intended.

Hope this helps

**Comment by ArcherEmiya05** [comment] 2021-06-01 12:16
> 
> 
> Hello @ArcherEmiya05 !
> 
> Thanks for reaching out and apologies for late response.
> Glad you made it work for you!
> Looking at your modified piece of code in your update makes me believe that in your case if you just specify your [ChatWindowEventsListener](https://github.com/livechat/chat-window-android#chatwindoweventslistener) and return `false` in your overwritten `handleUri` method this should work as intended.
> 
> Hope this helps

Does this mean I can do the same without modifying `ChatWindowView.class` file?

**Comment by nomyzs** [comment] 2021-06-01 12:19
Yes, you should be able to do the same without modifying this library.
Please note that new version is also available, `v2.1.5` being the latest release.

**Comment by nomyzs** [comment] 2021-06-30 17:26
Hoping above helped. Closing this for now, but please open another issue if you still facing this issue or found any others :)

**Closed by nomyzs** 2021-06-30 17:26 UTC
Labels: question
