### ISSUE TITLE
memory leak in chat-window-android:v2.0.0

### ISSUE THREAD

**Issue by Jerrychengjun** [livechat/chat-window-android#23] opened 2019-04-25 06:31 UTC
We integrated livechat SDK in our App ,and tested our app by monkey runner,we found some memory leak issues 
Here is some information

livechat SDK version :v2.0.0
leak log:
![image](https://user-images.githubusercontent.com/49055094/56717594-9926d300-676f-11e9-886c-59e677ac1ece.png)

**Comment by ZiggyKraus** [comment] 2019-04-25 07:11
@Jerrychengjun, it's me again. :) I will consult this case with our Android developer as well, but if that's OK, I'd like to ask if it would be possible for you to provide us with the test project in which this problem occurs. This would allow us to compile it at our side and see what may be causing the memory leak. You don't have to worry about this for now, but I'm asking just in case our developer would require it to diagnose this issue accurately – I will let you know if we would need this project as soon as I will get an update from our dev.

Also, please don't hesitate to let me know if you are not comfortable discussing the details of your mobile project via public GitHub repositories. We can switch the communication over to email if you prefer.

**Comment by nomyzs** [comment] 2019-04-25 13:04
Hey @Jerrychengjun !
Hope you're doing well.
What do you think about the following changes:
https://github.com/livechat/chat-window-android/commit/115834d48745b71dc14b33d06375280445c5d4b9
Basically adding an `onError` function to chat window listener and passing there errors from WebView.

Will that suite your needs? Any feedback on that?

**Comment by ZiggyKraus** [comment] 2019-05-02 13:15
Hello @Jerrychengjun!

I'm here with an update regarding the issue with memory leak and LiveChat widget.

Our developer was able to check the latest version of our chat widget and was not able to find any memory leaks that could have been caused by the LiveChat widget. Because of that, I'd like to ask if it would be possible for you to update the version of the chat widget used in your Android app, from **v. 2.0.0** to **v 2.0.4**. if the problem will still persist when using the latest version, we would like to ask if it would be possible for you to provide us with the sample project that we could compile at our side and in which we could detect the memory leak, as a specific configuration of some sort may cause this. 

Also, feel free to ask in case of any questions regarding the sample build that I've mentioned before, or in case of having questions regarding the Android SDK update – I will do my best to help!

**Comment by Jerrychengjun** [comment] 2019-05-05 01:53
Thank you for your reply.We fixed the memory leak by adding code "removeView(webViewPopup)" on following method,It seems to work.
hideChatWindow()
onCloseWindow()

**Comment by nomyzs** [comment] 2021-06-30 17:22
Good to hear you have resolved that issue on your own 💪 
I have double checked for memory leaks and could find anything alarming. 
Thus closing this issue now, but please feel free to open another one if that is still happening to you

**Closed by nomyzs** 2021-06-30 17:22 UTC
