### ISSUE TITLE
When open the keyboard chat does not rise

### ISSUE THREAD

**Issue by cardinaltm** [livechat/chat-window-android#18] opened 2019-03-21 03:19 UTC
Hello,
I have one problem, when open the keyboard chat does not rise
I tried to specify parameters in the manifest but not working
SDK version: 2.0.4

Image: https://ibb.co/xYwJ2dH

**Comment by nomyzs** [comment] 2020-02-26 18:43
Hello @cardinaltm 

Is this still happening to you? I couldn't reproduce your problem, and we have made a lot of improvements to our chat window since you posted that issue.
Please let us know if we should dig into it more. And of course, any tips on reproducing this would be helpful (device, android version, any steps)

**Comment by nomyzs** [comment] 2021-06-17 11:23
Hey @cardinaltm 
Hopefully this was solved in `v2.1.6` release. Refer to #62 for more details!

Closing this for now, but please comment on referred issue or create a new one if the problem is persisting.

**Closed by nomyzs** 2021-06-17 11:23 UTC
Labels: question
