### ISSUE TITLE
Failed to resolve: com.github.livechat:chat-window-android:v2.0.4

### ISSUE THREAD

**Issue by lvzesong** [livechat/chat-window-android#21] opened 2019-04-15 03:22 UTC
![271D504A-D087-49a4-A86A-5AD7BE3D9819](https://user-images.githubusercontent.com/15241976/56105795-b3430300-5f70-11e9-92fc-d1f9b7c20861.png)
![AC377C21-5338-4689-B0FA-61BD5167DA43](https://user-images.githubusercontent.com/15241976/56105801-b6d68a00-5f70-11e9-9e59-99c1aee78055.png)

**Comment by ZiggyKraus** [comment] 2019-04-19 17:33
Hello @lvzesong !

From the looks of it, it seems that the problem is caused by the following line of code used in your project:

`'com.github.livechat:chat-window-android:2.0.3'` if you could try to replace it with the following line:
`'com.github.livechat:chat-window-android:v2.0.4'` , run the project again and let us know if it helped, I will truly appreciate it! :)

**Comment by Zhipeng-Chang** [comment] 2019-05-09 22:33
hi @ZiggyKraus ! I'm running into the same problem even if I used "com.github.livechat:chat-window-android:v2.0.4"

**Comment by GiacomoK** [comment] 2019-09-10 10:08
Same problem here. I tried with 2.0.3 and 2.0.4 but I get the same error.

Btw you should edit the docs: "compile" directive is obsolute, you have to use "implementation".

**Comment by nomyzs** [comment] 2021-05-21 11:40
Hello!
As @ZiggyKraus suggested, please make sure to include `v` in Tag version. I imagine this can be troublesome, but we kept it for consistency.
@giacomok , we have updated documentation to use implementation instead of compile.
Thanks for your feedback! I this solves your problems. Going to close this issue, but please create another one if issue persist.

**Closed by nomyzs** 2021-05-21 11:40 UTC
